name: Generate Snake
   on:
     schedule:
       - cron: "0 */6 * * *"
     workflow_dispatch:
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: Platane/snk@master
           with:
             github_user_name: shobhit115
             outputs: |
               dist/github-contribution-grid-snake-dark.svg?palette=github-dark
